# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-12 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='User Name')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email_id', models.CharField(max_length=100, verbose_name='Email ID')),
                ('image', models.ImageField(default='img/user.jpg', upload_to='img/')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
